### ISSUE TITLE
设置->搜索引擎->编辑功能 “无法使用”

### ISSUE THREAD

**Issue by anquanbiji** [yeetime/sou2#18]
你好 
设置 -> 搜索引擎 ->选中一个引擎，点击右侧编辑 ,在点保存 会提示 “顺序:N 已有数据，不可用”  

需要将sou.js 如下代码删除
`     if (se_list[key]) {
            alert("顺序:" + key + " 已有数据，不可用");
            return;
        }
`

**Comment by yeetime** [comment]
done
